server:
  port: 8080
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login-microservice
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/auth/**
        - id: home-microservice
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**