version: '3.3'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'recorder'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'recorder'
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_ROOT_PASSWORD: 'recorder'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
